apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
        name: frontend
        namespace: app
        labels:
          app: frontend
    spec:
      containers:
        - name: frontend
          image: asia-northeast1-docker.pkg.dev/ksst-project-one/my-repository/vue-app:latest
          ports:
          - containerPort: 3001
          # livenessProbe:
          #   httpGet:
          #     port: 3001
          #     path: /
          #   failureThreshold: 5
          #   periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"