apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp-space
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
        name: myapp
        namespace: myapp-space
        labels:
          app: myapp
    spec:
      containers:
        - name: myapp
          image: bigface00/flask-vuejs:v1.1
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            failureThreshold: 5
            periodSeconds: 5