apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  namespace: app
  name: app-managed-cert
spec:
  domains:
    - xx.xx.xx.xx.nip.io # Please specify load balancer's external IP address.
