apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  type: NodePort
  selector:
    app: frontend # Transfer directions's laberl of pod
  ports:
    - protocol: TCP
      port: 3001 # Listening port number in the Service
      targetPort: 80 # Listening port number in the container
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
