version: '1'
services:
  frontend:
    image: asia-northeast1-docker.pkg.dev/ksst-project-one/my-repository/vue-app:latest
    build: ./frontend
    ports:
      - "8080:80"
  backend:
    image: asia-northeast1-docker.pkg.dev/ksst-project-one/my-repository/python-api:latest
    build: ./backend
    ports:
      - "5000:5000"
